#!/usr/bin/python

def add2(num1,num2):
   s=num1+num2
   return s


print add2(3,4)


def add3(num1,num2,num3):
    s1=num1+num2+num3
    return s1

print add3(4,4,3)

def add4(num1,num2,num3,num4):
    s2=num1+num2+num3+num4
    return s2

print add4(2,3,1,4)
